bigint
daniil-ushkov/first-term pull request #3
Opened 2020-06-29 13:40 UTC by daniil-ushkov

2020-06-29 20:16 UTC, kt-cpp requested changes
Комментарии с плашками [performance] и [semantic] требуют пояснений или исправлений. Остальное носит рекомендательный характер.

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.h
> +  big_integer &add_short_(uint32_t val);
[semantic] Этот метод должен быть публичным?

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  size_t i = (str[0] == '-' || str[0] == '+' ? 1 : 0);
[semantic] Пустая строчка всё сломает. Cледует явно кинуть исключение.

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  big_integer tmp(other);
[performance] В случае `&other == this` произойдёт излишнее копирование.

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    carry = static_cast<uint32_t>(tmp >> 32u);
[performance] Цикл не имеет смысла продолжать, если в какой-то момент выполнилось `carry == 0`

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  res.value_.push_back(carry);
[performance] `push_back` можно иногда избегать, так как бигинт всё равно будет приводиться в нормальную форму

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return *this = *this + rhs;
[semantic] Почему `+=` через `+`, а не наоборот?

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return *this -= 1;;
[style] `;;`

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return a - (-b);
[performance] То есть здесь копируется `b` в `operator-()`, копируется `a` в вызове `operator-(big_integer, big_integer&)`? Нельзя ли как-нибудь поаккуратнее?

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  a.value_.resize(std::max(a.size(), b.size()), 0);
[performance] Если в конце метода вызовется `push_back`, то произойдёт неизбежная переаллокация. Этого можно избежать здесь

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  big_integer res = *this;
[note] `push_back` вызовет переаллокацию всего вектора `res`. 
Если придумаешь, как это пофиксить, будет круто.

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return a + (-b);
[performance] То же замечание, что и в методе выше

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return -(b - a);
[performance] Ненужная копия от `operator-()`

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  big_integer res;
[minor] Не будет ли лучше использовать здесь где-нибудь `mul_short_`?

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  uint128_t const BASE = static_cast<uint128_t>(UINT32_MAX) + 1;
[semantic] Эту переменную можно сделать статической

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  if (b.size() == 1 && b.value_[0] == 0) {
[note] Числа всегда в нормальной форме?

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  uint64_t f = (static_cast<uint64_t>(UINT32_MAX) + 1) / (static_cast<uint64_t>(b.value_[m - 1]) + 1);
[semantic] Неявное использование `BASE` из функций выше

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  big_integer q, r = a * f, d = b * f;
[minor] Лучше инициализировать `q` один раз, иначе происходит лишняя аллокация-деаллокация одноэлементного вектора.

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +      word = ~word + 1;
[semantic] Дополнение до двух считается не так. Новый тест должен не пропускать такой код.

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer big_integer::bitwise_op(uint32_t (*op)(uint32_t, uint32_t), big_integer a, big_integer b) {
[minor] Можно уменьшить количество переаллокаций для `b`

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    a = -a;
[performance] `operator-()` имеет сложность `O(n)`

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    res.value_.push_back(0);
[performance] Можно избежать переаллокаций от последовательных `push_back`

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    res -= (uint64_t) (1ull << b % 32u) - 1;
[semantic] c-style cast

2020-06-29 20:16 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    ans += static_cast<char>('0' + big_integer(tmp).div_short_(10));
[performance] Зачем копировать `tmp`, если потом на нём делается `div_short_`? Это можно сделать оптимальнее.

2020-06-30 11:37 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  size_t i = (str[0] == '-' || str[0] == '+' ? 1 : 0);
fixed

2020-06-30 11:37 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  big_integer tmp(other);
fixed

2020-06-30 11:43 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    carry = static_cast<uint32_t>(tmp >> 32u);
fixed

2020-06-30 11:43 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  res.value_.push_back(carry);
fixed

2020-06-30 11:52 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  uint128_t const BASE = static_cast<uint128_t>(UINT32_MAX) + 1;
fixed

2020-06-30 11:52 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  uint64_t f = (static_cast<uint64_t>(UINT32_MAX) + 1) / (static_cast<uint64_t>(b.value_[m - 1]) + 1);
fixed

2020-06-30 11:52 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +      word = ~word + 1;
fixed

2020-06-30 11:54 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    res -= (uint64_t) (1ull << b % 32u) - 1;
fixed

2020-06-30 11:55 UTC, daniil-ushkov commented on bigint/big_integer.h
> +  big_integer &add_short_(uint32_t val);
fixed

2020-06-30 13:14 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  big_integer res = *this;
Кажется, что fixed

2020-06-30 13:24 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  return *this -= 1;;
fixed

2020-06-30 14:48 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    return a - (-b);
fixed

2020-06-30 17:13 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  a.value_.resize(std::max(a.size(), b.size()), 0);
fixed

2020-06-30 17:13 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    return a + (-b);
fixed

2020-06-30 17:14 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    res.value_.push_back(0);
fixed

2020-06-30 17:32 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    a = -a;
fixed

2020-06-30 17:34 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    ans += static_cast<char>('0' + big_integer(tmp).div_short_(10));
fixed

2020-06-30 18:18 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +big_integer big_integer::bitwise_op(uint32_t (*op)(uint32_t, uint32_t), big_integer a, big_integer b) {
fixed

2020-06-30 18:22 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    return -(b - a);
fixed

2020-06-30 18:22 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  return *this = *this + rhs;
fixed

2020-07-01 19:39 UTC, kt-cpp requested changes

2020-07-01 19:39 UTC, kt-cpp commented on bigint/big_integer.cpp
> +uint128_t const BASE = static_cast<uint128_t>(UINT32_MAX) + 1;
[note] Не уверен, рассказывали вам это или нет, но можно ограничить область видимости глобальной переменной до её единицы трансляции с помощью модификатора `static`. Просто интересный факт, можно не фиксить

2020-07-01 19:39 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  value_.resize(std::max(size(), rhs.size()), 0);
[minor] Я скорее имел здесь ввиду, что можно написать `std::max(size(), rhs.size()) + 1`, сразу заложив резерв для пушбэка

2020-07-01 19:39 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return *this = a;
[minor] Внутри конструктора копирования произойдёт лишняя копия a. Здесь можно сразу применить `swap trick`

2020-07-01 19:39 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    dst.sign_ = false;
[minor] Интересное жонглирование ссылками. Мне кажется, лучше было бы сразу присвоить `src.sign_` в какую-нибудь переменную и потом один раз сделать `dst.sign_ = false`, стало бы проще

2020-07-01 19:39 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    res.value_.push_back(value_[i]);
[note] Здесь можно вспомнить, что у тебя на самом деле вектор из чисел и применить низкоуровневые трюки вроде `memcpy`. Тем не менее, это плохо сочетается со следующим заданием, поэтому просто оставлю это как интересный факт.

2020-07-01 19:56 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  return *this = a;
fixed

2020-07-01 19:57 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  value_.resize(std::max(size(), rhs.size()), 0);
Ну, а сейчас я сделал умный резерв для пушбэка. Вроде это не хуже.

2020-07-01 19:57 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +    dst.sign_ = false;
fixed

2020-07-01 19:57 UTC, daniil-ushkov commented on bigint/big_integer.cpp
> +  value_.resize(std::max(size(), rhs.size()), 0);
В новой версии я еще повыносил общий код

2020-07-01 20:08 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  value_.resize(std::max(size(), rhs.size()), 0);
да, выглядит хорошо

2020-07-01 20:11 UTC, kt-cpp approved these changes

2020-07-01 20:12 UTC, merged